use_frameworks!
ENV['SWIFT_VERSION'] = '5.5.6'
platform :ios, '13.0'

target 'ExampleOC' do

  pod 'AgoraIotLink', :path => '../'
#  pod 'SJBaseVideoPlayer', :path => '../libs/SJBaseVideoPlayer'
#  pod 'SJVideoPlayer', :path => '../libs/SJVideoPlayer'
  pod 'SwiftDate'
  pod 'SDWebImageSwiftUI'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
