# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  # 解决 xcode13 Release模式下SwiftUI报错问题
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end

target 'AgoraIoT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraIoT
  pod 'SnapKit','5.6.0'
  pod 'IQKeyboardManagerSwift','6.5.9'
  pod 'HandyJSON','5.0.2'
  pod 'MJRefresh','3.7.5'
  pod 'AgoraIotSdk', :path=>'../'
  pod 'DZNEmptyDataSet','1.8.1'
  pod 'SVProgressHUD','2.2.5'
  pod 'Kingfisher','6.3.1'
  pod 'YYKit','1.0.9'
  pod 'JXSegmentedView','1.3.0'
  pod 'SJVideoPlayer','3.3.3'
  pod 'SwiftDate','6.3.1'
  pod 'ZLPhotoBrowser','4.3.1'
  
  pod 'AWSAuthCore','2.27.6'
  
end
