# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  # 解决 xcode13 Release模式下SwiftUI报错问题
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end

target 'IotLinkDemo' do
  use_frameworks!

  pod 'SnapKit','5.6.0'
  pod 'IQKeyboardManagerSwift','6.5.9'
  pod 'HandyJSON','5.0.2'
  pod 'MJRefresh','3.7.5'
  pod 'DZNEmptyDataSet','1.8.1'
  pod 'SVProgressHUD','2.2.5'
  pod 'Kingfisher', '7.4.0'
  pod 'YYKit','1.0.9'
  pod 'SwiftDate','6.3.1'
  pod 'ZLPhotoBrowser','4.3.1'
  pod 'SwiftyRSA','1.7.0'
  pod 'SSKeychain', :path => '../libs/sskeychain'
  
#  pod 'AgoraIotLink',:path=>'../'
  pod 'AgoraIot_iOS', :path => '../AgoraIot_iOS.podspec'
 
 
end
